name: publish_to_pages_test
description: Publish to cloudflare pages (Test)
inputs:
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account id'
    required: true
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare token'
    required: true
runs:
  using: composite
  steps:
  - name: Publish to cloudflare pages (test)
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
    run: |
      npm i wrangler@3.1.0
      cd packages/core
      npx wrangler pages deploy dist/ --project-name=deriv-app-pages --branch=test
      echo "New website - http://test.cf-pages-deriv-app.deriv.com"
    shell: bash
